name: Android Build

on:
  push:
    branches:
      - pipeline-dev

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v6

      # 2. Setup Java
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 4. Make Gradle executable
      - name: Grant execute permission
        run: chmod +x gradlew

      # 5. Build Profile APK
      - name: Build Profile APK
        run: ./gradlew assembleProfile

      # 6. Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-profile-apk
          path: app/build/outputs/apk/profile/app-profile.apk